name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: List Files
        run: ls -la
      
      - name: Debug
        run: |
          pwd
          ls -la
          find . -name "*.py"
          cat test_app.py

      - name: Show Test File
        run: cat test_app.py

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          pytest test_app.py -v  # or wherever your tests are located

  docker:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-flask:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/python-flask:latest

  deploy:

    needs: docker

    runs-on: ubuntu-latest

    steps:
      
      - name: Debug secrets
        run: |
          echo "HOST=${{secrets.EC2_HOST}}"
          echo "USER=${{secrets.EC2_USER}}"


      - name: Deploy To EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            docker pull ${{ secrets.DOCKER_USERNAME }}/python-flask:latest

            docker stop flask-app || true

            docker rm flask-app || true

            docker run -d \
              --name flask-app \
              -p 80:5000 \
              ${{ secrets.DOCKER_USERNAME }}/python-flask:latest
